fix(es,ts): remove posibility to create unused vars
akveo/styleguide pull request #25
Opened 2022-04-19 18:59 UTC by sashaqred

By default rule allow unused arguments `"args": "after-used"`:
```js
//         ⬇️ no error, because `index` is used
[].filter((item, index, array) => {
//                      ⬆️ eslint error of unused var
  console.log(index);
});
```

Also by default eslint will throw error on `foo`:
```js
const { foo, ...coords } = data;
```
Looks useful feature. So I configure rules to make this works.

And the last thing where unused variables are useful:
```
const [one, two, three] = [1, 2, 3];
console.log(one, three);
```
I couldn't find how to configure it properly. But in js there is a workaround:
```
//         ⬇️ second item is missed, not beautiful but as is
const [one, , three] = [1, 2, 3];
console.log(one, three);
```
I think it's not critical for the first release

2022-04-19 23:00 UTC, zankevich approved these changes

2022-04-20 11:04 UTC, malashkevich requested changes

2022-04-20 11:04 UTC, malashkevich commented on rules/typescript.js
> +  '@typescript-eslint/no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
Please change accordingly `typescript.md` in the Naming Style section:

https://github.com/akveo/styleguide/blob/master/typescript.md#naming-style-

2022-05-01 14:05 UTC, sashaqred commented on rules/typescript.js
> +  '@typescript-eslint/no-unused-vars': ['error', { 'ignoreRestSiblings': true }],
I've updated it

2022-05-18 11:29 UTC, malashkevich approved these changes

2022-05-18 11:58 UTC, merged